### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by tamal-appsbee** [maddevsio/go-idmatch#43]
Docker compose failed with following error:

# pkg-config --cflags  -- opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv4', required by 'virtual:world', not found
pkg-config: exit status 1

**Comment by Lezh1k** [comment]
Hello. 
Did you build opencv4 from sources or get it in some another way?

**Comment by tamal-appsbee** [comment]
It's working now, I did build from source and added "cmake -D OPENCV_ENABLE_NONFREE=1" before build

Thanks

**Comment by Lezh1k** [comment]
Should work with `-DOPENCV_GENERATE_PKGCONFIG=ON` 
OPENCV_ENABLE_NONFREE isn't related to that issue.

**Comment by tamal-appsbee** [comment]
ok, I shall try that out.
Thanks
